services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: metro-oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: ${ORACLE_PASSWORD}
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

  pg-db-auth:
    image: postgres:17
    container_name: metro-postgres-auth
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: authuser
      POSTGRES_DB: metrodbAuth
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./better-auth_migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  oracle-data:
  pg-data: