import dotenv from "dotenv";
dotenv.config();

import oracledb from "oracledb";

async function main() {
  console.log(process.env.ORACLE_CONNECTION_STRING);

  let connection;

  try {
    connection = await oracledb.getConnection({
      user: process.env.ORACLE_USER,
      password: process.env.ORACLE_PASSWORD,
      connectString: process.env.ORACLE_CONNECTION_STRING,
    });

    // Drop TIMETABLE_ACTION_LOGS if it exists
    await connection.execute(`
      BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE TIMETABLE_ACTION_LOGS CASCADE CONSTRAINTS';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE != -942 THEN
            RAISE;
          END IF;
      END;
    `);

    // Drop TIMETABLE_UPLOAD if it exists
    await connection.execute(`
      BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE TIMETABLE_UPLOAD CASCADE CONSTRAINTS';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE != -942 THEN
            RAISE;
          END IF;
      END;
    `);

    // Create upload table
    await connection.execute(`
      CREATE TABLE TIMETABLE_UPLOAD (
          UPLOAD_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

          UPLOAD_NAME VARCHAR2(100 BYTE) NOT NULL,

          LINE_ID NUMBER NOT NULL,

          RUN_DAY_TYPE NUMBER NOT NULL
              CHECK (RUN_DAY_TYPE IN (1,2,4)),

          TIMETABLE_DATA CLOB NOT NULL,

          STATUS VARCHAR2(20 BYTE)
              DEFAULT 'UPLOADED'
              NOT NULL
              CHECK (STATUS IN (
                  'UPLOADED',
                  'MODIFIED',
                  'DELETED',
                  'PUBLISHED'
              )),

          CREATED_BY VARCHAR2(100 BYTE),

          CREATED_AT TIMESTAMP
              DEFAULT CURRENT_TIMESTAMP
              NOT NULL,

          MODIFIED_BY VARCHAR2(100 BYTE),

          MODIFIED_AT TIMESTAMP,

          PUBLISHED_BY VARCHAR2(100 BYTE),
          PUBLISHED_AT TIMESTAMP,

          IS_DELETED NUMBER
              DEFAULT 0
              NOT NULL
              CHECK (IS_DELETED IN (0,1)),

          DELETED_BY VARCHAR2(100 BYTE),

          DELETED_AT TIMESTAMP
      )
    `);

    // Create action log table
    await connection.execute(`
      CREATE TABLE TIMETABLE_ACTION_LOGS (
          LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

          UPLOAD_ID NUMBER NOT NULL,

          ACTION_TYPE VARCHAR2(20 BYTE)
              NOT NULL
              CHECK (ACTION_TYPE IN (
                  'CREATE',
                  'MODIFY',
                  'DELETE',
                  'PUBLISH'
              )),

          ACTION_BY VARCHAR2(100 BYTE) NOT NULL,

          ACTION_AT TIMESTAMP
              DEFAULT CURRENT_TIMESTAMP
              NOT NULL,

          REMARKS VARCHAR2(500 BYTE),

          CONSTRAINT FK_TIMETABLE_ACTION_LOG_UPLOAD
              FOREIGN KEY (UPLOAD_ID)
              REFERENCES TIMETABLE_UPLOAD (UPLOAD_ID)
      )
    `);

    await connection.commit();

    console.log("✅ TIMETABLE_UPLOAD created");
    console.log("✅ TIMETABLE_ACTION_LOGS created");
  } catch (err: any) {
    console.error(err);
    console.error("Offset:", err.offset);
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

main();