import dotenv from "dotenv";
dotenv.config();
import oracledb from "oracledb";

async function main() {


  console.log(process.env.ORACLE_CONNECTION_STRING);
  let connection;

  try {
    connection = await oracledb.getConnection({
      user: process.env.ORACLE_USER,
      password: process.env.ORACLE_PASSWORD,
      connectString: process.env.ORACLE_CONNECTION_STRING,
    });

    await connection.execute(`
      CREATE TABLE TIMETABLE_UPLOAD
      (
          UPLOAD_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

          UPLOAD_NAME VARCHAR2(100 BYTE) NOT NULL,

          LINE_ID NUMBER NOT NULL,

          RUN_DAY_TYPE NUMBER NOT NULL
              CHECK (RUN_DAY_TYPE IN (1,2,4)),

          TIMETABLE_DATA CLOB NOT NULL,

          CREATED_BY VARCHAR2(100 BYTE),

          CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
      )
    `);

    console.log("✅ TIMETABLE_UPLOAD created");

  } catch (err) {
    console.error(err);
  } finally {
    await connection?.close();
  }
}

main();